### ISSUE TITLE
GCC 12 - Issues Raised by Address Sanitizer

### ISSUE THREAD

**Issue by jens-erdmann** [scanoss/wayuu#12]
Hi there,

wayuu fails to build with GCC 12, which is the default on debian testing. It seems to be caused by the address sanitizer in combination with `-Werror`:
```
builder@1d5395bad7f2:/tmp/wayuu-master$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

builder@1d5395bad7f2:/tmp/wayuu-master$ make
rm -f *.o **/*.so **/*.o test/*.o test/**/*.o  wayuu test-wayuu
gcc -g -Wall -fPIC -Werror -std=gnu99 -DWAYUU_DIST -o conf_parser.o -c conf_parser.c
gcc -g -Wall -fPIC -Werror -std=gnu99 -DWAYUU_DIST -o file_utils.o -c file_utils.c
gcc -g -Wall -fPIC -Werror -std=gnu99 -DWAYUU_DIST -o http_utils.o -c http_utils.c
http_utils.c: In function 'wayuu_error_t_json_serializer':
http_utils.c:484:25: error: the comparison will always evaluate as 'false' for the address of 'code' will never be NULL [-Werror=address]
  484 |         if (error->code == NULL || strlen(error->code) == 0)
      |                         ^~
In file included from wayuu_log.h:27,
                 from http_utils.c:30:
http_utils.h:97:8: note: 'code' declared here
   97 |   char code[HTTP_MAX_ERROR_CODE_LEN];
      |        ^~~~
http_utils.c: In function 'return_response':
http_utils.c:548:13: error: the comparison will always evaluate as 'true' for the address of 'text' will never be NULL [-Werror=address]
  548 |         if (rsp.text)
      |             ^~~
http_utils.h:223:9: note: 'text' declared here
  223 |    char text[50];
      |         ^~~~
http_utils.c:550:13: error: the comparison will always evaluate as 'true' for the address of 'description' will never be NULL [-Werror=address]
  550 |         if (rsp.description)
      |             ^~~
http_utils.h:224:9: note: 'description' declared here
  224 |    char description[256];
      |         ^~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:39: http_utils.o] Error 1
```

**Comment by scanoss-qg** [comment]
Hi @jens-erdmann. Thanks for your interest on Wayuu. We have an update ready on a branch to solve your issue. However, we would like to know wich version of ssl you are using (just type on the console: **openssl version** ) We are asking this because removing the -Werror flag from the compilation also hides a deprecation usage error. The branch presented [here](https://github.com/scanoss/wayuu/tree/AddressSanitizer) will compile with Openssl 1.1.1 and GCC-12, but consider that Version 1.1.1 will be deprecated by September 2023. We are preparing an update for the functions that will be deprecated.

**Comment by scanoss-qg** [comment]
Hi @jens-erdmann. We have released Wayuu v1.5. This new version solves the issues reported by you. 
Consider that you can also find a Golang based API on our Github. Thank you so much for your contribution.

**Comment by jens-erdmann** [comment]
Can confirm. Problem is solved.
